version: "3.6"
services:
  mastodon-halobug:
    image: nginx:1.21.4-alpine
    restart: always
    expose:
      - 80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nginx.index.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik
      - mastodon_networks
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.mastodon-halobug.entrypoints=https"
      - "traefik.http.routers.mastodon-halobug.tls=true"
      - "traefik.http.routers.mastodon-halobug.rule=Host(`chat.halobug.cn`)"
      - "traefik.http.services.mastodon-halobug-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.mastodon-halobug-backend.loadbalancer.server.port=80"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
networks:
  mastodon_networks:
    external: true
  traefik:
    external: true
