version: "3"

services:

  mastodon-minio-nginx:
    image: nginx:1.21.4-alpine
    volumes:
       - ./nginx.minio.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - traefik
      - mastodon_networks
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.mastodon-oss-http.entrypoints=http"
      - "traefik.http.routers.mastodon-oss-http.rule=Host(`oss.halobug.cn`)"
      - "traefik.http.routers.mastodon-oss-https.entrypoints=https"
      - "traefik.http.routers.mastodon-oss-https.tls=true"
      - "traefik.http.routers.mastodon-oss-https.rule=Host(`oss.halobug.cn`)"
      - "traefik.http.services.mastodon-oss-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.mastodon-oss-backend.loadbalancer.server.port=80"
    depends_on:
      - minio
  minio:
    image: minio/minio:RELEASE.2022-01-08T03-11-54Z
    volumes:
      - ./minio/data:/data:z
    command: minio server /data --address 0.0.0.0:80 --listeners 1  --console-address 0.0.0.0:9001
    environment:
      MINIO_ROOT_USER: umf3V1C3Hu5TzCDDqIXFbDDviYGhV627
      MINIO_ROOT_PASSWORD: OqIwA1GJADWgCf5yvlRTKTJ6bTYAhaO9exqX5lo3GlOlLfVcIbn4v2CsuamB
      MINIO_REGION_NAME: cn-homelab-1
      MINIO_BROWSER: on
      MINIO_BROWSER_REDIRECT_URL: https://mastodon-s3.halobug.cn
      MINIO_PROMETHEUS_AUTH_TYPE: public
    restart: always
    ports:
      - 9001:9001
    expose:
      - 80
    networks:
      - traefik
      - mastodon_networks
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.minio-gzip.compress=true"
      - "traefik.http.routers.minio-admin.middlewares=minio-gzip"
      - "traefik.http.routers.minio-admin.entrypoints=https"
      - "traefik.http.routers.minio-admin.tls=true"
      - "traefik.http.routers.minio-admin.rule=Host(`mastodon-s3.halobug.cn`)"
      - "traefik.http.routers.minio-admin.service=minio-admin-backend"
      - "traefik.http.services.minio-admin-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.minio-admin-backend.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/minio/health/live"]
      interval: 3s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
networks:
  traefik:
    external: true
  mastodon_networks:
    external: true
